### ISSUE TITLE
Need Language Version Disclaimer

### ISSUE THREAD

**Issue by dlemire60** [oasis-open/openc2-lycan-python#14]
The OpenC2 leadership needs your help to clarify the relationship of this repo's code to the current language definition. With public review of our specifications imminent, the TC's repos need to be clearly labeled to indicate their alignment or lack thereof with the current language specification.

If your code aligns with an older version of the language, please add the following disclaimer to the start of the "Statement Of Purpose" section of your README.md file:

```This repository contains code developed against an earlier version of the OpenC2 language than that presented by OASIS for public review in October / November 2018 and is NOT CONSISTENT WITH THE VERSION UNDERGOING PUBLIC REVIEW. Any implementer of OpenC2 using this code should be aware that it will require updating to align with the current OpenC2 Language Specification.```

If your code already aligns with the current language specification, (i) thank you, and (ii) it would be helpful for you to add a statement to that effect to your README.md.

If it is possible for you to update your code to align with the language specification that would be a welcome contribution. The TC leadership recognizes that many of the repos contain code for inactive projects that do not have any resources available to apply to updating the code.

**Comment by mstair** [comment]
Addressed with #12
